name: Continous Integration

on: push

jobs:
  test:
    name: Test on commit
    runs-on: ubuntu-18.04
    steps:
      - name: npm install
        run: npm install
      - name: npm test
        run: npm run test
